### ISSUE TITLE
Doesn't Seem to be Working

### ISSUE THREAD

**Issue by Morabert** [Albeoris/Memoria.FrontMission1#1]
Not Sure What I'm doing out of order here:
![explorer_9D6j1QHEz3](https://github.com/Albeoris/Memoria.FrontMission1/assets/36409264/896e02fe-d8ee-435f-90c2-93c63a5cb2c0)

**Comment by LunarWhisper** [comment]
You need to extract release files to the game folder, not the sources:
https://github.com/Albeoris/Memoria.FrontMission1/releases/download/v2023.07.28/Memoria.FrontMission1.Steam_GOG_v2023.07.28.zip

**Comment by Albeoris** [comment]
@Morabert , what are you trying to do? Build it from the sources or install a mod?
If you want to install the mod, please look at the instruction.
You need to extract 2 archives: BeepInEx and the latest version of the mod. For example, this one:
[Memoria.FrontMission1.Steam_GOG_v2023.07.28.zip](https://github.com/Albeoris/Memoria.FrontMission1/releases/download/v2023.07.28/Memoria.FrontMission1.Steam_GOG_v2023.07.28.zip)

But you extracted sources to the game folder. :)
